### ISSUE TITLE
Finding your Balls Quest

### ISSUE THREAD

**Issue by JJM152** [JJM152/Queen#104]
See overall mutiny quest #52 

- [x] When balls / penis shrink to a certain level, play an event in the morning that starts the quest chain.
- [x] Talk to julius about removing chastity cage
- [x] bring him some chemicals from Apothecary in Golden Isle.
- [x] He unlocks cage as payment and you ask him about what to do about your shrinking manhood. He then informs you to go to David Jone's locker and ask about any rare goods that might help.
- [x] At David Jone's locker, get told to search caverns in Abamond for special ore to make magic cock ring.
- [x] Find ore in Caverns, return to Jameson and he (for fee) creates the ring.

- [x] Ring stats (LEGENDARY accessory)
- Prevents Penis growth xp from accumulating (negative or positive)

**Comment by ezsh** [comment]
I feel that willpower value has to play a role in these events.

**Comment by JJM152** [comment]
> I feel that willpower value has to play a role in these events.

Okay I'll bite, how would you suggest?

I think the game could use more nods to WillPower myself, so I'm very interested in your ideas.

**Comment by ezsh** [comment]
> When balls / penis shrink to a certain level, play an event in the morning that starts the quest chain.

Here we can put a willpower test. If the value is low, the ptotagonist accepts the fate.

> Talk to julius about removing chastity cage

Here, IMO, a combination of pervertion and willpower tests would suit.

> Find ore in Caverns…

If this is going to include a randomiser (the protagonist is not a geologist after all, finding an ore has to depend on luck), failing an attempt to find the ore drains willpower, thus requiring a high value to pass. Successful digging outcome restores willpower. Or digging attempts could drain a resource computed out of the willpower value.
