### ISSUE TITLE
Error wearing clothes

### ISSUE THREAD

**Issue by JJM152** [JJM152/Queen#105]
"Error: <<WearingTable>>: errors within widget contents (Error: <<WearingChange>>: error within widget contents (Error: <<if>>: bad conditional expression in <<if>> clause: Cannot read property 'Slot' of undefined); Error: <<WearingChange>>: error within widget contents (Error: <<if>>: bad conditional expression in <<if>> clause: Cannot read property 'Slot' of undefined); Error: <<WearingChange>>: error within widget contents (Error: <<if>>: bad conditional expression in <<if>> clause: Cannot read property 'Slot' of undefined); Error: <<WearingChange>>: error within widget contents (Error: <<if>>: bad conditional expression in <<if>> clause: Cannot read property 'Slot' of undefined); Error: <<WearingChange>>: error within widget contents (Error: <<if>>: bad conditional expression in <<if>> clause: Cannot read property 'Slot' of undefined); Error: <<WearingChange>>: error within widget contents (Error: <<if>>: bad conditional expression in <<if>> clause: Cannot read property 'Slot' of undefined); Error: <<WearingChange>>: error within widget contents (Error: <<if>>: bad conditional expression in <<if>> clause: Cannot read property 'Slot' of undefined); Error: <<WearingChange>>: error within widget contents (Error: <<if>>: bad conditional expression in <<if>> clause: Cannot read property 'Slot' of undefined); Error: <<WearingChange>>: error within widget contents (Error: <<if>>: bad conditional expression in <<if>> clause: Cannot read property 'Slot' of undefined); Error: <<WearingChange>>: error within widget contents (Error: <<if>>: bad conditional expression in <<if>> clause: Cannot read property 'Slot' of undefined); Error: <<WearingChange>>: error within widget contents (Error: <<if>>: bad conditional expression in <<if>> clause: Cannot read property 'Slot' of undefined); Error: <<WearingChange>>: error within widget contents (Error: <<if>>: bad conditional expression in <<if>> clause: Cannot read property 'Slot' of undefined); Error: <<WearingChange>>: error within widget contents (Error: <<if>>: bad conditional expression in <<if>> clause: Cannot read property 'Slot' of undefined); Error: <<WearingChange>>: error within widget contents (Error: <<if>>: bad conditional expression in <<if>> clause: Cannot read property 'Slot' of undefined))"

**Comment by JJM152** [comment]
@ezsh reopened this ticket and put screenshot in here.
Hey, at least it's a different bug than last time. :)

![image](https://user-images.githubusercontent.com/8572919/46583821-a0221880-ca9f-11e8-98e3-e75e5b143013.png)

**Comment by ezsh** [comment]
I can't reproduce that yet :(

**Comment by JJM152** [comment]
Steps I am doing to reproduce.
- Start Game
- Select Pathetic Loser difficulty
- Skip Intro
- Open Lootbox
- Enter Wardrobe
- Click 'Change'
- Select 'fishnet tights'

**Comment by ezsh** [comment]
But the fix is obvious: do not add duplicates to the `slotsToUndress` variable or clean-up clothes definitions to make sure no item have a restriction on its own slot.
