### ISSUE TITLE
Possible Quest / Story Arc Idea for the original GF / Jarvis / Rowe

### ISSUE THREAD

**Issue by Grengras** [JJM152/Queen#113]
Due to the way you found those... odd... things in the GF's room in an early story arc, a second story arc becomes possible. What if the girlfriend was not really the daughter of Lord Rowe after all? What if she was either a guy once upon a time herself, or simply a girl who was forced into the sick games of that family?

Potential ideas include that Rowe has a thing for fucking his own daughter and Jarvis has been supplying him with replacements as needed.

One possible side arc for this could become very dark. Find one or more body(ies) in a hidden room of girls (and/or sissies) who all have been made to look the same and preserved through some macaub art form / act. (Perhaps taxidermy?) The story arc would reveal that one of the reasons the "girl" had so been desperate to elope with the player in the beginning was because she found out the time before she would be the next victim was nearly at an end.

The main arc would still be dark in that the player is somehow forced or blackmailed into pretending to be the daughter, but no actual deaths would be involved.

Either way... once the arc starts the player needs to quickly find a way out and reveal the evil history / plans of Jarvis and / or Lord Rowe.

Good result has the player unmasking the evils of the men and perhaps gaining freedom or even becoming governor for your efforts.

Potential bad result from failing to reveal the dirty secrets publically would be that the player gets handed over into the care of Jarvis / Rowe and now is on a short deadline to find some way of escape even while being forced to act like the loving, dutiful, and virginal daughter that the original girlfriend seemed to be to the player character in the prologue.

This could in turn result in having to find some gullible young boy to believe you were in love with him and wanted to elope ala the prologue figuring that having to marry him would be not as bad as the alternative.

Another alternative could be that Jarvis informs the player that he would allow your freedom if you help arrange to have a replacement daughter to take your place. This would result in your beau "randomly" finding the same Salty Mermaid captain and arranging passage from the prologue. The events from the original prologue would be repeated but this time the player would see events from the POV of the original GF and a new npc would experience the events from POV of the player's prologue.

If you did this loop arc possibility, it would allow for the player to be "betrayed" once back on the ship and drugged and sold off to a brothel... where he'd meet the original gf... along with dozens of other "girls" all of whom once upon a time was Lord Rowe's "daughter" or some other similar wealthy men after getting bored with them and wanting a new replacement. All of the other whores the player meets here went through the same experience that the player did. This would either be a Bad End or possibly the player could arrange a mass escape or alternatively brothel takeover where the player then becomes the madam of the house arranging for the other girls to work for her.

Sound good? Or bad or overly complicated idea?

**Comment by JJM152** [comment]
Thanks for the idea.
