### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by ezsh** [JJM152/Queen#115]
I propose to consider migrating the sources to TypeScript. That would, of course, require a build system, most likely force to install and use npm.

**Comment by JJM152** [comment]
I use TypeScript at work, but I'm rejecting this for this project.

One of the initial purposes of it was to make everything accessible to people who wanted a good example of how to build a complex Twine game using just Tweego. I still want to hold to that idea as much as possible and I think TypeScript (or any other transpiler) would go against that mission.

**Comment by ezsh** [comment]
OK, maybe next time...
