### ISSUE TITLE
New Clothing Suggestions Thread

### ISSUE THREAD

**Issue by Grengras** [JJM152/Queen#122]
I thought it would be a good idea to start a centralized thread for people to place their suggestions for new clothing items.

I'll start it off with 2 suggestions for the Daddy's Girl set.

//Neck
App.Data.Clothes["dg collar"] = { // +9
    "Name": "collar for daddy", "ShortDesc": "a lacey {COLOR} collar with pink hearts",
        "LongDesc": "This lacey white collar is fashioned with little pink hearts that combine to form the words '@@color:pink;Daddy's Girl@@!' as a whole.",
        "Slot": "Neck", "Restrict": ["Neck"], "Color": "white", "Style": "UNCOMMON", "Type" : "ACCESSORY",
"Category" : [ "Daddy's Girl" ], "WearEffect": [ "FEMININE_CLOTHING", "KINKY_CLOTHING" ]
};

//CORSET
App.Data.Clothes["precious belt"] = { // +9
    "Name": "belt with glitter", "ShortDesc": "a {COLOR} belt with glittery letters",
    "LongDesc": "This white belt features pink glitter spelling out the word '@@color:pink;PRECIOUS@@'.",
    "Slot": "Corset", "Restrict": ["Corset"], "Color": "white", "Style": "RARE", "Type" : "ACCESSORY",
    "WearEffect": [ "FEMININE_CLOTHING", "WAIST_CINCHING" ], "Category" :  [ "Daddy's Girl", "Bimbo", "Pet Girl",  ]
};

As an aside... If these two items don't get added I feel like 'something' needs to be added to this set. Currently you can have naturally blond hair in pigtails and everything else in the set and still not be able to do the daddy's girl quest (Only 91 with regular shoes, 96 with platforms). It makes no sense that a wig has to be worn even when it is the exact same style and hair length as the natural hair it is replacing.

**Comment by JJM152** [comment]
You have a git hub account, so why not fork this repo and put together a pull request with the new items?
