### ISSUE TITLE
AssFirmness implementation needs fixing

### ISSUE THREAD

**Issue by JJM152** [JJM152/Queen#150]
I had to comment this out. Short story is - You can't use the body stats leveling config for a meta stat as the game will try to level it overnight. No step leveling and no default values means it crashes the sleeping page.

I like the idea, generally, of meta statistics and displaying them/alerting people to their changes, it's just not supported without some modifications.

**Comment by ezsh** [comment]
Hm.. I'm puzzled, because I do remember that this problem (attempting to level the ass firmness) did not exist when I played. Where do XP points for it come from? The leveling code processes only stats it finds in  the  `PlayerState.xxxXP` objects, right?

**Comment by JJM152** [comment]
Could it be related to the version upgrade code adding an AssFirmness statistic to the player object from the body stats?

**Comment by ezsh** [comment]
Exactly right!

**Comment by ezsh** [comment]
Er... Reverted 0f9e52f06ee35c4cd66bf493618e0648fcd71856 (which disables the stat), but what do I need to do to reproduce the problem? I can't make it level "AssFirmness" using neither a new game nor a save from 0.7.

**Comment by ezsh** [comment]
But I do remember that back in November I was deleting the said property from the PlayerState object when playing.

**Comment by JJM152** [comment]
Wish I could remember the steps I did to make it happen.

The simplest solution is probably just to make the leveling routine ignore statistics that do not have a MIN or MAX stat associated with them?

**Comment by ezsh** [comment]
Playing from the beginning with the ass firmness brought back and can't catch the bug :  yet. Thus I'm going to implement your suggestion (" to make the leveling routine ignore statistics that do not have a MIN or MAX stat associated with them").

**Comment by JJM152** [comment]
Sounds good, I like the idea and want to see it back.
👍

**Comment by ezsh** [comment]
Found it! `SetStartingStats()` sets `BodyStats.AssFirmness` to NaN and this leads to the rest of it.
