### ISSUE TITLE
Shop UI is broken by 44d82d970c39f1fdc9a1c5c6c18d3ae1ecafde4b

### ISSUE THREAD

**Issue by ezsh** [JJM152/Queen#151]
@JJM152 , I did not understand what did you try to achieve and therefore can't fix. Reverting the specified commit fixes the UI. Otherwise I get "Error: `<<storeInventory>>: errors within widget contents (Error: cannot find a closing tag for HTML <span>; Error: cannot find a closing tag for HTML <span>)"`

**Comment by JJM152** [comment]
I'll take a look at it, but it was "working on my machine" when I did the last push to the master branch.

**Comment by JJM152** [comment]
Yeah I'm not seeing an issue here, what shop were you looking at specifically?

![image](https://user-images.githubusercontent.com/8572919/52634646-74aeaf00-2f13-11e9-97be-fb5e88b3843e.png)

**Comment by ezsh** [comment]
Diabled 'Inline detailed information in inventory and shops' setting triggers this.

**Comment by JJM152** [comment]
Ahh... of course. Fixed.
