### ISSUE TITLE
locked state of clothing not being saved when moved to wardrobe

### ISSUE THREAD

**Issue by JJM152** [JJM152/Queen#152]
I only realized this because I implemented a quest to unlock the chastity cage. 

I would prefer that this state be retained when transferred to the inventory, but perhaps an alternative work around would be to refactor the locked items so that they are by default unlocked and then locked when added to the player during setup? Primarily this affects the chastity cage and slave collar for now, at least I think so.... maybe we need to do a text search to confirm.

Can you take a look at this since you wrote the clothing manager class? 

Thanks

**Comment by ezsh** [comment]
It was intentional, as I though it is impossible to take off a locked item. And I still believe this is logical. Maybe we need a special method to take off a enchanted/locked item? This method can retain the lock state.

**Comment by JJM152** [comment]
> It was intentional, as I though it is impossible to take off a locked item. And I still believe this is logical. Maybe we need a special method to take off a enchanted/locked item? This method can retain the lock state.

Seems like an over engineered solution for only 2 use cases that matter (the collar and the chastity cage). If I'm reading the way this code works correctly, then items that are worn retain their locked state in the player state file, which is fine. It just means that we need to, for those two items, explicitly lock them when a character is first created..

**Comment by ezsh** [comment]
> Seems like an over engineered solution for only 2 use cases…

Quite the opposite, as there was no need to keep the locked state at all. Now I'll add the "Locked" property to each item, while only two of them need that.

**Comment by JJM152** [comment]
Not sure what you're on about. The player state has a property already for if an item is locked. I'm saying leverage that instead of using the Locked property on items. 

![image](https://user-images.githubusercontent.com/8572919/52913579-131f8380-330b-11e9-976c-738b43e4b903.png)

**Comment by ezsh** [comment]
Those are equipped items, while the`Wardrobe` property (unequipped ones) just lists IDs.

**Comment by ezsh** [comment]
If the locked state does not change by unequipping an item, is there any way to unlock an item at all? If no, we can just check the item record in the `App.Data` and if it is locked, set its locked flag when equipping the item.

**Comment by JJM152** [comment]
> Those are equipped items, while the`Wardrobe` property (unequipped ones) just lists IDs.

Yeah I know. There's no reason to know if an item in the wardrobe is "locked". That's a state that only applies to something that is currently being worn, because we assume that if it's not worn then it's unlocked. 

The only reason why there is a Locked property at all is because in the first iteration of the item system I was just instatiating objects directly and it was a property of the item and not the user. It made sense in that case to have it then, but not so much now.



> If the locked state is not changed by unequipping an item, is there any way to unlock an item at all? If no, we can just check the item record in the `App.Data` and if it is locked, set its locked flag when equipping the item.

There is specifically a method I added to the Player wrapper to do just this.

`    SetLock(Slot, Lock) {
        this.Clothing.SetLock(Slot, Lock);
    }`

You could pretty much remove all of the locking related code from the `Wear() `routines and just implicitly lock those 2 items at character creation directly. I guess we'll have to alter the class in the Item file as well to make the short description make sense because if something is not worn, it's not locked.

**Comment by ezsh** [comment]
Then refering to the `App.Data` entry when puttying an item on seems to be fine. And later, as you say, we can add another property "Lockable" to the same list, if required. Do you agree?

**Comment by JJM152** [comment]
> Then refering to the `App.Data` entry when puttying an item on seems to be fine. And later, as you say, we can add another property "Lockable" to the same list, if required. Do you agree?

I'm not sure I understand how that is supposed to work, because if an item is unlocked, then it will be locked again the next time you put it on since it will have a Locked=true property, which is not the intended behavior.

The workaround that I'm thinking of is to just set those two item's properties to false, then lock them after the item records are created in the equipment state, but that leaves an amount of unused code in the Player.js file.

**Comment by ezsh** [comment]
> …then it will be locked again the next time you put it on…

I though this is what you want to get. Now I'm lost completely. Could you tell me, please, what is the locked state for an item in the following sequences of state changes?

1. New game, lockable item is put on. State: locked (this is obvious).
1. The item is exchanged with another of the same kind (e.g. a collar). State?
1. The item is taken off. State?
1. The item is put on again. State?

**Comment by JJM152** [comment]
Yeah I could tell that you weren't quite getting what I had intended here. I'll do my best to try and explain it here - 

1. New Game - Item is locked when added to player.
2. The new item gets locked, the old item gets unlocked and placed in wardrobe. (This is how the collar swap programmed into the game originally worked).
3. Item's can't be removed unless they are unlocked first. 
4. Item is still unlocked.

You have to remember going back to the original implementation of the clothing system - the "Locked" property did not signify that the item should be locked, it was used to keep track of the "Locked" state of the item because the item states got written out to the save file. That's the only reason why that property existed in the first place. 

I don't think it needs to exist any more and testing if an item is locked with `IsLocked()` can be just a getter that routes through the manager to the Equipment state's "Locked" property instead.

**Comment by ezsh** [comment]
Thank you for the answers, but they only deepened my confusion, because 3 and 4 contradict the issue title, or it's just me?

**Comment by JJM152** [comment]
Maybe the issue title is poorly worded. What I meant is this, I set an object to be Locked=false, but when it went to the wardrobe it became Locked=true (the state was not saved).

**Comment by ezsh** [comment]
Great! Now it all makes sense. Thank you for the explainations! I was confused by the wording in the title of the starting post.

**Comment by JJM152** [comment]
Cool. 👍 

So... then what do you think needs to be done to make this work? I have my own idea, but back to my original question - you wrote this so what do you think?

**Comment by ezsh** [comment]
Hope #157 does make the exact change you've asked for. Because I'm still unsure I understood you right :D

**Comment by JJM152** [comment]
I'll do some testing with the new quest I implemented to unlock the cage item.

**Comment by ezsh** [comment]
I got to this quest myself testing everything from the beginnig and something seems to be wrong. The ring is in inventory, but the slot is locked in the wardrobe UI. How is that supposed to work?

**Comment by ezsh** [comment]
See #230.
