### ISSUE TITLE
Bonus and minimum aren't applied for loot boxes.

### ISSUE THREAD

**Issue by BulkScuba** [JJM152/Queen#156]
I believe the cause is here: https://github.com/JJM152/Queen/blob/6aaa4a7f502ffb6de71a14c3fb71c2b734b13443/src/000-SCRIPT_OBJ/Items.js#L321
Probably the "if (player.debugMode == true)" with some body was put in for debugging, and the body was removed but the condition left in.

This makes all the loot box rarities effectively the same.

**Comment by JJM152** [comment]
Good catch. I think there was probably a console statement there that got removed.
