### ISSUE TITLE
display issue - Desperation line overlaps desperation spin

### ISSUE THREAD

**Issue by Jamie-Martin** [JJM152/Queen#167]
Firefox 65.0.1, Windows 64 bit, a thousand addons, etc.
Get to desperation spin level, get hit a good bit, go to inventory to take a few herbs, exit back to whoring window, red bar displays over the text by quite a bit

![queen 9 2019-02-25_desperation_spin_overwritten](https://user-images.githubusercontent.com/43938472/53394646-de947300-396d-11e9-8baa-136d7e5f5a28.png)

**Comment by JJM152** [comment]
I'll look into this, but it may be a CSS thing related to FireFox and Jquery that I can't really fix.

**Comment by JJM152** [comment]
I could really reproduce this, so I'll need some help from someone else if they can do so, or even provide me with css that they think will rectify it without messing up chrome.
