### ISSUE TITLE
UI: can't load a save until finishing the prologue

### ISSUE THREAD

**Issue by ezsh** [JJM152/Queen#180]
...because the control links are not shown

**Comment by ezsh** [comment]
At lease the link "Skip the intro and begin the game" in the first passage would be helpful.

**Comment by ezsh** [comment]
Maybe we'd better restyle the SugarCube buttons to make them much smaller (so they fit in a single line) instead of removing them completely?

**Comment by JJM152** [comment]
I'll add a load button. I don't want to restyle the buttons, I actually prefer them looking like the other links in the ui. Gimme a few.

**Comment by ezsh** [comment]
Could you move the links down then, please?
