### ISSUE TITLE
Source mapping in Chrome and Firefox does not work

### ISSUE THREAD

**Issue by ezsh** [JJM152/Queen#181]
Including the da module leads to broken source mapping in these two browsers (and I have no others to test). 

Previously, typing a function name in console I was able to jump to its definition, set a breakpoint and debug it. Now any function maps to the same line in the matrix.js module:
```
// Node support
if (typeof exports !== "undefined") exports.Matrix = Matrix;
```

It is a major problem for me, as I'm unable to debug and have to use logging instead :(

**Comment by JJM152** [comment]
I'm open to suggestions - originally it was much worse, every console error was being caught by the webpack module resolver and completely untraceable. I was able to get around this by modifying my local copy of DA and rebuilding it with different options.

Maybe try asking in the dynamic avatar drawer thread if he has any suggestions?

**Comment by ezsh** [comment]
Aha! So it comes from webpack... Thanks, I'll try to dig in that direction.

**Comment by ezsh** [comment]
With this change for the DAD:
```diff
diff --git a/webpack.config.js b/webpack.config.js
index 96e7d82..d1466bf 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -34,7 +34,7 @@ module.exports = {
         ]
     },
     watch       : true,
-    devtool     : 'inline-module-source-map',
+    devtool     : 'eval-cheap-module-source-map',
     module      : {
         rules: [
             {
```
the source mapping in Queen seems to be back. But I have no idea what does my change do.

https://webpack.js.org/configuration/devtool/

**Comment by ezsh** [comment]
BTW,  running `npm run build` and copying `dist/da.js` into the Queen sources does not work for me 
 but results in 
```
Uncaught TypeError: PartPrototype is not a constructor
    at Object.create (part.js?a7a5:111)
    at Avatar._AttachParts (eval at call.output.output (Queen.html:5), <anonymous>:284:28)
    at Avatar._DrawPortrait (eval at call.output.output (Queen.html:5), <anonymous>:230:19)
    at Object.Avatar.SettingHandler (eval at call.output.output (Queen.html:5), <anonymous>:46:28)
```
Could you share how do I need to build the da sources, please?

**Comment by JJM152** [comment]
That looks promising. I'll mess around with it over here as well.

I should probably set up a fork for DAD. Do you have any idea what the workflow would look like considering it's hosted on gitlab? I get as far as changing the upstreams and doing a `git push origin master` but I'm still left wondering:

- What's the best/easiest way to merge changes into this customized fork?
- What's the most sensible approach for building DA.js and injecting it into the Queen.html build chain. Hmm, using appveyor seems easy enough to script it, but what about locally? Rely on having downloaded the branch to a specific area an then use relative paths in build.bat/sh ? Is there a clever(er) way to do this? Script the entire download from the DA fork, build and then copy into the tweego compile path? 

I dunno, there are a lot of options I guess.

**Comment by JJM152** [comment]
> BTW, running `npm run build` and copying `dist/da.js` into the Queen sources does not work for me
> but results in
> 
> ```
> Uncaught TypeError: PartPrototype is not a constructor
>     at Object.create (part.js?a7a5:111)
>     at Avatar._AttachParts (eval at call.output.output (Queen.html:5), <anonymous>:284:28)
>     at Avatar._DrawPortrait (eval at call.output.output (Queen.html:5), <anonymous>:230:19)
>     at Object.Avatar.SettingHandler (eval at call.output.output (Queen.html:5), <anonymous>:46:28)
> ```
> Could you share how do I need to build the da sources, please?

- Make sure you do an npm install first
- Copy code from Queen/daCustom into da/src
- npm run build
- copy dist/da.js into Queen

I have a little local bat file that does this, but see my previous comment as well, I think this should be changed.

**Comment by ezsh** [comment]
Thanks! I was wondering what is this daCustom dir for.  

>  I get as far as changing the upstreams and doing a git push origin master but I'm still left wondering:

I would just use two remotes for the local clone: origin for your fork and upstream for the DAD repo at GitLab. Then `git fetch upstream`, `git checkout master` (optionally, obviously), `git merge upstream/master`, `git push` is the way I would do that. 

> What's the most sensible approach for building DA.js and injecting it into the Queen.html build chain. 

Don't know what to suggest here. A git submodule (pointing to the fork) and a change to the `build.bat` (and I could reflect that in the `build.sh`) would be OK for me. I don't know is there a way to make `npm run build` in the DAD repo work faster when there is no changes. I would not want to have it in the Queen build chain if it takes more then a few seconds.

> What's the best/easiest way to merge changes into this customized fork?

Git merge or rebase, whatever you prefer. I see no way to avoid manual merging.

**Comment by ezsh** [comment]
Please correct the file name in the `index.js` (case sensitivity):
```
ERROR in ./index.js
Module not found: Error: Can't resolve './player/bimbochest' in '/home/eugene/games/dynamic-avatar-drawer/src'
 @ ./index.js 36:0-36 36:0-36
```

**Comment by ezsh** [comment]
and why is it referenced in directory `player` while the file is in `daCustom/parts`?

**Comment by JJM152** [comment]
> and why is it referenced in directory `player` while the file is in `daCustom/parts`?

Like I wrote previously, I'm currently running a local bat file that copies that file, daCustom/src/parts/bimboChest.js into ~/da/src/parts/

That export reference in index.js shouldn't be case sensitive, I think you're just missing the file that it's referencing.

**Comment by ezsh** [comment]
The path in the `index.js` is wrong:
```
export * from "./player/bimbochest";
```

**Comment by PerplexedPeach** [comment]
Hi DAD dev here (separate github account for less socially accepted projects I guess),
so here's the setup I recommend:

```
├─── DAD (full fork, existing as a git submodule in this repository)
│     ├─── src (put assets you think other people can use in src)
│     ├─── dist (where da.js will be outputted and where you should target in build.sh)
├─── src
│     ├─── 000-SCRIPT_OBJ (put extensions and project only assets here)
```

So then the development would be:
1. fork DAD on gitlab
2. clone fork as git submodule into this repository
3. make shareable changes inside the fork
4. temporarily make project-specific changes inside `test.html` for ease of testing
5. `npm start test` to test your changes in the GUI (rebundling is instantaneous now since it doesn't try to rebundle everything anymore, and you don't have to manually refresh the page)
6. iterate 3-5 until satisfied
7. move project-specific changes out
8. `npm run build` to build `dist/da.js` for production
9. `build.sh` (optionally have it run step 8, but it's run in watch mode right now so it won't terminate)

Commits to the fork can be merged back to the original project by submitting a merge request on gitlab.
