### ISSUE TITLE
DAD not working properly

### ISSUE THREAD

**Issue by ArallaiSwamplest** [JJM152/Queen#182]
So i played version 0.9b and the save file from it has DAD working without the clothes but when i load it in version 0.9c or 0.9d the DAD is just showing a grey background without the player character tried a completely blank save file and it is working properly so probably some value is not working properly.

Dont know how else to send the save file so here it is.

ezsh: replaced the inline save contents with an attachment
[queen-dad.save.zip](https://github.com/JJM152/Queen/files/2923050/queen-dad.save.zip)

**Comment by JJM152** [comment]
Thanks. It's a bug with the 'Ring' part that DAD supplies, we're trying to use them as nipple rings and it looks like it's having a calculation error on the new huge boobs part that I added.

Short story: Remove the rings and it will work for you.

Longer story: I'm going to remove them from the latest build and then build a new part to handle them in the future (It's already logged as an issue).

Thanks for reporting this.
