### ISSUE TITLE
Extend DA before da.load

### ISSUE THREAD

**Issue by PerplexedPeach** [JJM152/Queen#185]
You should extend DAD (and add patterns) before calling `da.load` so you don't have to have that busy loop:
```
            var patternInterval = setInterval(function() {
                for(var i = 0; i < App.Data.AvatarPatterns.length; i++) {
                    if (da.listAvailablePatterns().includes(App.Data.AvatarPatterns[i] == false)) return;
                }
                console.log("All DA Patterns Loaded");
                App.Avatar.Loaded = true;
                clearInterval(patternInterval);
            }, 20);
```

The point of `da.load` as a promise is so that in the `then` part it's guaranteed that all loading (extensions and patterns) have been resolved.

How should I change the extension/content creation guide to make this more clear?

**Comment by JJM152** [comment]
Yeah, I shouldn't have left that laying around, it doesn't do anything. 

> How should I change the extension/content creation guide to make this more clear?

Well, some sort of understanding of the loading pipeline would be good probably? A better example with verbose comments of what's going on? Maybe a simple sample project implementing the library? Diagrams? Charts? Smoke signals?

> The point of da.load as a promise is so that in the then part it's guaranteed that all loading (extensions and patterns) have been resolved.

Like above, I didn't understand that I could load my patterns before calling da.load, I assumed incorrectly I needed to load first, then add my own stuff. I'm not sure why I thought this and I'm not sure it was explicitly stated what the order of things were in the documentation I read, or if it was, I just skipped over it. Who knows?

Come to think of it, in my particular implementation it would probably be more useful to have your engine throw an event when it's done loading.
