### ISSUE TITLE
Fork DAD Repo - set up work flow

### ISSUE THREAD

**Issue by JJM152** [JJM152/Queen#186]
Look at the closed ticket #181 for some off-topic discussion about this.

Summary: Set up a proper workflow for DAD

Below is proposed from the author of DAD:

-------

Hi DAD dev here (separate github account for less socially accepted projects I guess),
so here's the setup I recommend:

```
├─── DAD (full fork, existing as a git submodule in this repository)
│     ├─── src (put assets you think other people can use in src)
│     ├─── dist (where da.js will be outputted and where you should target in build.sh)
├─── src
│     ├─── 000-SCRIPT_OBJ (put extensions and project only assets here)
```

Then the development process would be:
1. fork DAD on gitlab
2. clone fork as git submodule into this repository
3. make shareable changes inside the fork
4. temporarily make project-specific changes inside `dist/test.html` for ease of testing
5. `npm start test` to test your changes in the GUI (rebundling is instantaneous now since it doesn't try to rebundle everything anymore, and you don't have to manually refresh the page)
6. iterate 3-5 until satisfied
7. move project-specific changes out
8. `npm run build` to build `dist/da.js` for production
9. `build.sh` (optionally have it run step 8, but it's run in watch mode right now so it won't terminate)

Commits to the fork can be merged back to the original project by submitting a merge request on gitlab.

Since this issue topic's derailed anyway, on another note what IDE/tools are you guys using?

_Originally posted by @PerplexedPeach in https://github.com/JJM152/Queen/issues/181#issuecomment-469401632_

**Comment by JJM152** [comment]
@PerplexedPeach - eh, I finally got around to doing this. Do you want anything from my fork? I just have those whacky oversized breasts and a twine specific webpack config.

**Comment by LemonPi** [comment]
I think it's fine for now, but you can keep pull requests in mind if you create some assets that you think other projects might also use :D. Thanks for doing this btw, I know how easy it is to run out of steam...

**Comment by JJM152** [comment]
sure, I'll keep that in mind.

I did send you a PR on gitlab however for an easy defect i found. I'll push back any more obvious bugs I find.

cheers
