### ISSUE TITLE
Rebalance Will Power and Toxicity

### ISSUE THREAD

**Issue by JJM152** [JJM152/Queen#187]
Problem: Management of these stats is too easy due to an explosion in items that deal with them. The stat management aspect of the game is suffering because of this. Let's tighten it up a bit.

Suggestions:

**Toxicity**
- [x] Remove the damage component from `Player.DoHealing()` method and put into separate effect. 
- [x] Below 100 toxicity only retards healing and damages energy.
- [x] Above 100 toxicity also does possible fatal health damage.
- [x] Add some minor toxicity components to all TF items. Especially drugs.
- [x] Gruel should be slightly toxic. Basically anything edible that isn't marked as `WHOLESOME_MEAL` or `LIGHT_WHOLESOME_MEAL` is fair game. perhaps add a new effect `UNWHOLESOME_MEAL` with a minor 5 toxicity (less than `TOXICITY_COMMON`) The knowledge effect should be red and called 'Unwholesome Meal' to let players know.

**WillPower**
- [x] Reduce availability of hard alcohol.
- [x] Increase toxicity of hard alcohol.
- [x] Add a new method called `CorruptWillPower()`
- [x] Funnel APPROPRIATE will power decreases through here.
- [x] Add default willpower hits for sex acts based on perversion

Pseudo:

```
CorruptWillPower(XP, Difficulty = 50)
{
    mod = this.GetStat('STAT','Perversion')/Difficulty;
    diff = Math.ceil(XP - (XP * mod)/2);
    if (diff < 0) {
            AdjustXP('STAT', 'WillPower', diff, 0, true); // make sure to bypass caps and limits
            AdjustXP('STAT', 'Perversion', Math.abs(diff), 0, true);
            //Add a flag to the player state with the current Day on it to capture on the overnight 
            //SleepLog that your antics caused you to lose some willpower and get more perverted.
   }
}
```

I have been slowly adjust and changing job scenes and dialog to look at the players perversion score to add more flavor into the game. Previous iteration of the game used to block the player from undertake certain actions unless this score was high enough, but that felt way too limiting and led to people 'grinding perversion'. Instead, let's just reflect what's happening by altering dialog here and there?

**Comment by ezsh** [comment]
Completing certain quests (like "Boarding pass", sex-related ones if perversion is high enough) could boost willpower.

**Comment by JJM152** [comment]
Yeah I agree.

**Comment by ezsh** [comment]
Another idea: if we suppose that all the changes induced by drugs are kind of mutations, it is natural to assume that accumulating many of them in a body should decrease their efficiency due to accumulated genetic "noise".  So their transformation power (XP amount) decreases the more drugs are taken. This means at some point there will be no turning back in transforming for the player character. Or we can add a kind of cleaning (complicated alchemistry? complex voodoo?).

So, I propose to add a new body stat that defines the transformation efficiency and each call to `AdjustStatXP("BODY", ...)` will also add a (negative) XP to this stat. Its value in turn is used as a coefficient (stat/1000, for example) for XP points in `AdjustStatXP("BODY", ...)`.

**Comment by ezsh** [comment]
Forgot to mention in the previous post that this new proposed stat is something related to toxicity, and that's why I wrote about that here.

**Comment by JJM152** [comment]
I think that thematically making transformation harder is not something that I want to accomplish in this game. In fact I made it a bit easier to revert changes in a recent commit or two because I thought it was too hard.

What I kind of want to do is add some more encounters to the game that adds/drains/shifts XP from body parts. Conceptually I'm thinking of adding monsters that have these type of status effects as attacks.

For example, in the simple Rogue-like, add some mob enemies (combat done by bumping into each other). That when they hit shrink your boobs, or move your ass growth to your waist, or inject male or female hormones.

In this kind of scenario, I'd want players to be able to revert "damage" done this way as part of the games meta gameplay. Also, it will make exploring the caverns more interesting and the mobs can also drop loot.

**Comment by ezsh** [comment]
Thanks for the detailed reply! Like those ideas. My only question to this setting (of easy changes) is why does the game have zero mentions of other characters transformations? As I remember, there was an idea at some point to transform Reginald, which would be cool. And I would support a quest line centered around finding the (already transformed?) girlfriend, buying her out of slavery (or something like that), and, of course, transforming her.

**Comment by JJM152** [comment]
> As I remember, there was an idea at some point to transform Reginald, which would be cool. And I would support a quest line centered around finding the (already transformed?) girlfriend, buying her out of slavery (or something like that), and, of course, transforming her.

The Reginald thing is still on the roadmap and I like the girlfriend idea. It's just like everything else - it takes time to put content into the game.

Anyway, with the addition of DAD to the game, both of these options would probably be pretty entertaining.
