### ISSUE TITLE
NPC speech highlighting does not work for the BETTER_LOCKER quest

### ISSUE THREAD

**Issue by ezsh** [JJM152/Queen#193]
Apparently, because the regex for that wants it to start with a blank space, while in this quest the "s(" sequence is at the beginning of the string.

**Comment by JJM152** [comment]
K, I'll look at it.

**Comment by ezsh** [comment]
Maybe we'd better choose a more "inhuman" keyword for the speech markup? then we can safely drop the space requirement.

**Comment by JJM152** [comment]
I don't disagree, I just chose that because it was easier to remember. I find that being the hardest part of actually writing a job - remembering all the tokens and json options that are available. I'm somewhat inclined to just fix the existing regex pattern though 🤷‍♂️

**Comment by ezsh** [comment]
Hmm, then I would change the bracket type, perhaps. For instance, `s[` is not what I expect to encounter in description of pirate or islander life.

**Comment by JJM152** [comment]
Decided to fix this by just removing the leading whitespace. I couldn't find any instances where it would normally break something gramatically.
