### ISSUE TITLE
Journal does not show accurate indicator for worn items

### ISSUE THREAD

**Issue by bbampfade** [JJM152/Queen#195]
The Uticus quest in the journal does not acknowledge when the player has the "voodoo anal plug" equipped.

The actual NPC quest turn in showed "READY TO TURN IN" just fine, but the journal seemed to think the item wasn't equipped.

**Comment by ezsh** [comment]
Please let us know the game version.

**Comment by JJM152** [comment]
I'm pretty sure I fixed this in a commit this last week.
