### ISSUE TITLE
Autosaves

### ISSUE THREAD

**Issue by ezsh** [JJM152/Queen#198]
It makes sense to enable autosave for debugging purposes. From the other hand, daily autosave would remove much of spice from the game, but such saves would make most sense for debugging. What if we enable autosave for every week or 10 days and add a parameter to the cheat room to control the autosave period?

**Comment by JJM152** [comment]
If you want to use it for just testing, then just enable it from the cheat room only.

**Comment by ezsh** [comment]
Periodic autosave would be nice for a regular game, just not every day. I'll try to implement and use that and let us see how that will work, OK? Seems like you don't have direct objections?

**Comment by JJM152** [comment]
Sorry, I wasn't clear - I don't like autosave as a feature, but that's not really true - I would turn it on, but only if I disabled the load/save button and replaced it with a continue /new game option on the start page, which is probably not what you're thinking.
