### ISSUE TITLE
Warn when torches are about to go out

### ISSUE THREAD

**Issue by JJM152** [JJM152/Queen#210]
When a torch gets down to it's last 10 rounds, every round print something like 'Your torch is flickering and about to go out' to the chat buffer at the bottom of the screen.

**Comment by ezsh** [comment]
We can make it tremble by changing the light range every move, gradually decreasing it down to zero.

**Comment by JJM152** [comment]
@ezsh didn't you complete this in a PR a while ago? Or some similar mechanic?

**Comment by ezsh** [comment]
No, I did not. My only contribution is the comment above.
