### ISSUE TITLE
Measurements are transposed, indicating insane dimensions

### ISSUE THREAD

**Issue by Huntarr** [JJM152/Queen#214]
currently showing feet as inches and inches as feet.

The foot (pl. feet; abbreviation: ft; symbol: ′, the prime symbol) is a unit of length in the imperial and US customary systems of measurement.

The inch (abbreviation: in or ″) is a unit of length in the (British) imperial and United States customary systems of measurement.

**Comment by ezsh** [comment]
Thanks for reporting. The bug was fixed by #188.

**Comment by Huntarr** [comment]
Rog, Sorry.  I went thru the issues and couldn't find it.

**Comment by ezsh** [comment]
There was no open issue for this bug.
