### ISSUE TITLE
Tweego set-up

### ISSUE THREAD

**Issue by CapeOmnia** [JJM152/Queen#236]
Hi, I've been playing the game for a bit and now I was trying to see if I could understand the code to maybe help out here and there with easy stuff. I've started with just adding characters en a store.

Now I want to 'make' the html file but I get this in my cmd (directory structure included):

C:\Users\Jeroe>cd Documents\Queen

C:\Users\Jeroe\Documents\Queen>tweego TWEEGO_PATH C:\Users\Jeroe\Documents\Queen\storyformats
warning: path TWEEGO_PATH: GetFileAttributesEx TWEEGO_PATH: The system cannot find the file specified.
warning: Replacing existing passage "format.js" with duplicate.
warning: Replacing existing passage "icon" with duplicate.
warning: Replacing existing passage "format.js" with duplicate.
warning: Replacing existing passage "icon" with duplicate.
warning: Replacing existing passage "format.js" with duplicate.
warning: Replacing existing passage "icon" with duplicate.
warning: Replacing existing passage "format.js" with duplicate.
warning: Replacing existing passage "icon" with duplicate.
warning: Replacing existing passage "format.js" with duplicate.
warning: Replacing existing passage "icon" with duplicate.
warning: Replacing existing passage "format.js" with duplicate.
warning: Replacing existing passage "icon" with duplicate.
error: Starting passage "Start" not found.

C:\Users\Jeroe\Documents\Queen>dir
 Volume in drive C has no label.
 Volume Serial Number is E20B-1B8B

 Directory of C:\Users\Jeroe\Documents\Queen

09-04-2019  17:15    <DIR>          .
09-04-2019  17:15    <DIR>          ..
09-04-2019  16:14               397 .gitattributes
09-04-2019  17:21             4.619 .gitignore
09-04-2019  16:57    <DIR>          .idea
09-04-2019  16:14               932 appveyor.yml
09-04-2019  16:14                39 build.bat
09-04-2019  16:14                57 build.sh
09-04-2019  16:14    <DIR>          daCustom
09-04-2019  16:14            18.431 LICENSE
09-04-2019  16:14             1.930 README.md
09-04-2019  16:14    <DIR>          scripts
09-04-2019  16:14    <DIR>          src
29-01-2019  23:28    <DIR>          storyformats
09-03-2018  14:56         3.920.384 tweego.exe
               8 File(s)      3.946.789 bytes
               7 Dir(s)  176.148.004.864 bytes free

What is going wrong and how can I fix it?

Edit: How do I label it as question?

**Comment by ezsh** [comment]
If `tweego TWEEGO_PATH` is what you input in the terminal, that is wrong. The `TWEEGO_PATH` environment variable, of present, should contain path to the dir with story formats (this dir shall contain `sugarcube-2` subdir). What you need to run is in the `build.bat`, which resides in the root of the repository.

With the file layout you shown above, you can just run `build.bat` and it should work.

**Comment by CapeOmnia** [comment]
That did it. Thank you
