### ISSUE TITLE
 Escubac d'Angleterre tooltip

### ISSUE THREAD

**Issue by test23412** [JJM152/Queen#261]
The tooltip shows an increase in toxicity, but due to the HEAL_RARE effect in the end it lowers the toxicity.

This is just an example, obviously the tooltip is only derived from the effect, but when the effect is a combination of multiple effects, those are not summed up to show the end result.

**Comment by JJM152** [comment]
Probably wont work on this one, not much of a return for the amount of effort required to modify this.
