### ISSUE TITLE
Ability to remove and swap out chastity cage

### ISSUE THREAD

**Issue by JJM152** [JJM152/Queen#31]
This should likely be initially tied to a quest that allows you to unlock the cage, from there you can swap out different cages for various bonuses related to the item in question.

**Comment by Grengras** [comment]
I agree that would be ideal for a more permanent end game solution to allow a player to swap things on their penis whenever they want.

However, couldn't you also use the same system already in place for collar changes to do a temporary fix for the players with the chastity as well? By that I mean swap the locked on item effects for a different penis worn item such as the ribbon. They still couldn't remove the item, and only could be swapped on a single island store, but it would allow them to nullify the crushing effects of the locked on cage for different effects instead.

**Comment by JJM152** [comment]
closed by commit 18832fec21e7bbc2bc685b952f12f3792eb0464a
