### ISSUE TITLE
Eating food in cabin can send you back to a previous location

### ISSUE THREAD

**Issue by JJM152** [JJM152/Queen#41]
Erratic bug - eating food will occasionally send you to the wrong bookmark location, which should be impossible. 

Might be a sugarcube related bug with the state history.

**another report**
Just replicated the position thing on first attempt: bought food from Cookie, went to cabin, rested until night (twice I think), went to food, ate one or two stew, click exit, wind up back at Cookie.
Nutrition was below three, I ate to get it up to 3.

**Comment by ezsh** [comment]
> Might be a sugarcube related bug with the state history.

I compile with Tweego 1.3.0/Sugarcube 2.27.0 and have never encountered anything like that.

**Comment by JJM152** [comment]
User still reporting this as a problem in test release. 

I'm going to assume this is a bug in the SugarCube state engine and therefor I'm going to write some custom code in the window namespace to handle this.

That's the only thing I can think of at this point.

**Comment by ezsh** [comment]
I can neither find anything suspicious nor reproduce this. Tried various browsers, downloading official release, building the file myself. 
My suggestion is to add logging to the `GameBookmark` manipulations before rewriting and try to get logs from those who can make the bug happen.

**Comment by ezsh** [comment]
> My suggestion is to add logging to the GameBookmark manipulations 

They do that by themselves already, huh?

**Comment by JJM152** [comment]
Yup, sometimes two pairs of eyes really help.

I think the correct way to do this is to replace the tokens [[Rest]] and [[Sleep]] in the Cabin description with the <<customMenuLink>> widget.

Thanks for that.

**Comment by ezsh** [comment]
My pleasure.
