### ISSUE TITLE
Inventory filtering

### ISSUE THREAD

**Issue by JJM152** [JJM152/Queen#43]
Add the ability to filter and order inventory a bit, even searching I guess if possible. Try to apply this to all tabs. Maybe add a "favorites" to move certain items to the top of the list?

**Comment by ezsh** [comment]
Implemented favorites for items (no favorites for the wardrobe yet, and I'm not sure they are needed). As for the filtering, I think the only useful one would be by item effect. But I'm puzzled how to implement that:
1. List known effects? There could be many of them, filtering in a filter is stupid.
2. Filter by description in a hope that effect is mentioned there?
3. Sorting by effect strength would be nice to get.

Maybe we can use icons for effects and output those in the inventory tables? Then sorting and filtering would make sense.

**Comment by JJM152** [comment]
Honestly, I think the favorites are enough and I agree, I don't think the wardrobe items need them (at least not in the gear tab, since you can't wear from there anyway, only the wardrobe). There is nothing that seems really obvious to me other than alphabetizing.

Just adding a note here to myself, you don't have to do this if you don't want:

- Make sure WardrobeItemsBySlot sorts alphabetically when returning array
- Add collapsing panels to gui in Inventory for Wardrobe items (not worn)
- Considering removing GetItemByName and replaces calls to it with GetItemById

**Comment by ezsh** [comment]
I submitted a PR that sorts `WardrobeItemsBySlot()` results, as that was very easy. As for the panels, I don't understand what do you want and thus can't implement that. Removing `GetItemByName()` involves refacoring various engines, and I'm not sure I can do that not making mistakes.

**Comment by ezsh** [comment]
With a real game save I have to admit that sorting by item tag is not perfect, because tags differ from the visible description strings. From the other hand, sorting by item description gives even worse result because of prepended articles and adjectives.

**Comment by JJM152** [comment]
> From the other hand, sorting by item description gives even worse result because of prepended articles and adjectives.

What about sorting on Name() ? Have you tried that?

This was the original purpose of that attribute - a simple name that could be used when referring to an object in dialogs or text strings that were not descriptions.

**Comment by Grengras** [comment]
Not sure how your Favorites system works yet. So if I am requesting something similar to what you have already put in place I apologize.

But any possibility of a simple but permanent filter that makes things invisible to the player?

I'm imagining a "[Hide]" or a "[-]" button next to every object in the inventory. When the player clicks that button the object permanently does not show up in the inventory list even though it is still there. Next have maybe a new toggle choice for "View Hidden" to the right of last current option of Gear. When click into this tab it would display all Hidden objects for each of the other tabs when click on them but none that have not been hidden yet. To return to only seeing non-hidden objects would just click on the Hidden toggle a second time. (Might need to have it say "Normal View" or something so people know how to get out of their hidden items list.)

**Comment by ezsh** [comment]
To fit that into the game setting, we could enable the favorites and the option to hide items via quests to get some fun out of it and let players feel some reward? For example, favorites could be obtained via a quest with Julius to get some boxes or shelves for your locker, and the hidden inventory via a quest to obtain a second locker.

**Comment by JJM152** [comment]
I really like the idea of inventory upgrade quests.  Totally has my support.

Maybe open up a new ticket if you want for a future enhancement, I'll close this one for now as it appears good when I was testing today..
