### ISSUE TITLE
Ratings for nouns

### ISSUE THREAD

**Issue by ezsh** [JJM152/Queen#55]
To spice up texts a bit I propose to implement ratings for nouns that would be similar to the way ADJECTIVE works now. The idea is too put, say, `nASS` in a text and let `TokenizeString()` replace it with a leveling noun (that would reflect the size). 

I'm working on that and currently have the following implemented:
1. Replacing `n[A-Z_]` with a string from a corresponding rating object with adjectives prepended.
2. Replacing `NOUN` with the noun itself and `NOUN_([A-Z_])` with name of the body stat in brackets (camel cased as GameData.js uses).
3. Replacing `ADJECTIVE_([A-Z_])` in a similar way.
4. Nouns may depend on several ratings. For example, noun for bust may depend on their size and firmness (new stat).
5. Rating records for nouns and adjectives may contain arrays as the final entries. In that case random element is selected. This adds some variations to the texts.
6. Replacing `v([A-Z_])` with the value of the corresponding stat. Allows to use Twine conditionals (`<<if vSOMETHING > X>>`) in the strings.

My problem with that is my bad English, which makes it hard for me to fill all those tables with appropriate words. 

@JJM152, you can have a look [here](https://github.com/ezsh/Queen/blob/master/src/000-SCRIPT_OBJ/Helpers.js#L932) and [here](https://github.com/ezsh/Queen/blob/master/src/001-SCRIPT_DATA/GameData.js#L1438).

**Comment by JJM152** [comment]
This sounds good. I noticed you added a new statistic for bust firmness is that also part of what you're proposing or just something that's current in-dev on your branch? How would that work?

**Comment by ezsh** [comment]
With the bust firmness I not only want to add some fun, but also break the possibility to infinitly earn money and food doing the first mate evening job and then doing miling in the morning. The idea with the firmness is that the milking quickly decreases the firmness, which in turn leads to lowering mood outcomes from dancing and money gain from other sexual activities. The too low or too high firmness affects fetish rating. The firmness decreases [on itself](https://github.com/ezsh/Queen/blob/master/src/001-SCRIPT_DATA/EFFECTS/effects_body_natural.js#L79) and needs threatments to maintain.

**Comment by JJM152** [comment]
Not a bad idea, but maybe a little bit too micro-mange-y (not a word) for my tastes, depending on how it's balanced.

How would you relate this back to skill/job effects? Currently payment is scaled on skill rolls, and bust does add some bonus to some of them. I don't think there are many straight bust checks...

The fetish rating stuff makes sense.

I had a similar idea to you as to breaking up that loop. I mean, yes, there is a willpower hit (or at least I believe there was) from Kiplers whoring quest, but I was thinking about adding a game over state with a transformation to a hucow if you let yourself get milked too many times with low willpower.

**Comment by JJM152** [comment]
Btw, the nouny verby stuff is great - just wanted to separate those two issues.

**Comment by ezsh** [comment]
> How would you relate this back to skill/job effects?

Pardon, I will start with another topic. It looks to me that willpower penalty should decrease with perversion increase (but not disappear, of course). I was thinking that we can easily add that and declare either as
```
 { "TYPE" : "STAT_XP",    "NAME" : "WillPower",  "VALUE" : -50, "OPT" : "RANDOM" },
 { "TYPE" : "STAT_XP",    "NAME" : "WillPower",  "VALUE" : 0.1, "OPT" : "FACTOR",  "FACTOR" : "STAT/Perversion" },
```
Returning to the body stats, it can be done in a similar way (`"FACTOR" : "BODY/BustFirmness"`). 
Regardless of the job/quest outcomes, the stat, I believe, might give fun for those who are into it (i.e. both implants and sagginess lovers). 

The hucow development seems good to me, but now it is very easy to maintain high willpower value once the second unlock in the Julius shop is uncloked.

**Comment by JJM152** [comment]
That's fine.

**Comment by ezsh** [comment]
The first part is in #128.

**Comment by JJM152** [comment]
Had a good crack at this. Closing it for now.
