### ISSUE TITLE
Fixes for item / inventory refactor

### ISSUE THREAD

**Issue by JJM152** [JJM152/Queen#58]
Charges not showing up in inventory gui
Opening lootbox prints items, but they don't get added to inventory.

reference #46

**Comment by JJM152** [comment]
Found cause of bug. The key for the dictionary entry of the item and the 'name' attribute for the object the entry refers to were never intended to be the same, but they're being used in the refactor that way. 

I'll see how much I have to refactor of the overall code in order to fix this.

**Comment by ezsh** [comment]
Shopping is broken too, because the Shop class calls `Player.AddItem(Type, Name, 0)` and the function interprets 0 literally. I don't understand what does that zero mean and therefore should the `Shop.BuyItem()` be changed to call ``Player.AddItem(Type, Name, 1)` or do I need to handle 0 in the `AddItem()` as unity?

**Comment by JJM152** [comment]
That's an easy fix, I'll do it on my local. The arguments are just the keys to the dictionary and then the number of items to create. It can probably just be omitted now. I'll look at it.

I started refactoring the code to make a differentiation between an items Name and it's Tag, using the tag basically as the key instead of the name. That should solve most of the problems I have with the inventory right now.

Just let me hack this back into shape so it's all functional I guess. Anything as messy as this in the future we should probably merge to a test fork, so my bad on not insisting on that.

**Comment by ezsh** [comment]
> … and then the number of items to create. 

So, what's the meaning of 0 as the number of items (as the `Store.BuyItem()` passes) then?

> Anything as messy as this in the future we should probably merge to a test fork…

I will mark my WIP PRs in a more clear way in the future.

**Comment by JJM152** [comment]
> I will mark my WIP PRs in a more clear way in the future.

In retrospect, yes, but also in retrospect, if I had been a managing this properly it wouldn't be an issue. It's something for me to think about.

> So, what's the meaning of 0 as the number of items (as the `Store.BuyItem()` passes) then?

I'm **guessing** here that this may have had to do with stacking charges on some items that come with more than 1. Probably a hack I put in when I wanted to set makeup to be +5 charges per purchase (as defined in the data dictionary) instead of adding the default 1 charge.

But frankly, I can't say for sure. A lot of this stuff was literally "write it once to get it working really fast and never look back".

**Comment by ezsh** [comment]
Thanks! So, "0" means "take charges from the item definition". It is absolutetly escaped my sight and should be added to the manager classes. But I'll wait for your refactor commits first.

**Comment by JJM152** [comment]
Taking a little bit longer than I intended to get done because I decided to clean up some of the jsdoc  since all the ESlint errors in my ide are giving me the absolute shits.

I'll make sure to update this ticket with a note about what I think is still broken for you to take a look at, but then I'm going to move on to trying to put a dent in my project board for the next release. :hammer_and_pick:

**Comment by JJM152** [comment]
So, I just added commit f3b5974. This should have gotten the inventory and shop interfaces working again. 

Things I have not tested yet:

- Does buying items with more than 1 charge (like makeup) give 5 items or 1.
- Can you buy clothing.
- Do the shop lock out (remove) clothing from interfaces that you already own.
- Does the bazaar/market interface still work?
- Do jobs / quests that give items still work?
- Can you still get new slot reels and remove them correctly?
- Does the wardrobe work?

I did notice a couple of things:
- Slot interface doesn't show if you have more than 1 item now of the same type. Before it listed them all like separate entities. 
- It seems that when I reload the app, I lose all my items? I didn't check to see if they are not being saved to the playerstate, or if the inventory manager is just not recreating them correctly.

I want to try and push a release before I leave on vacation next week, so I'm going to start beavering away on the new game content. Hope I can  leave the rest of this up to you, @ezsh? Thanks!

PS: Will leave this issue open for now until we close this off.

**Comment by ezsh** [comment]
Thanks, I will test all those things. Some of them were tested already:
- [ ] Does buying items with more than 1 charge (like makeup) give 5 items or 1. **No, it doesn't work**
- [ ] Can you buy clothing.
- [x] Do the shop lock out (remove) clothing from interfaces that you already own. **Locks**
- [x] Does the bazaar/market interface still work?
- [ ] Do jobs / quests that give items still work?
- [x] Can you still get new slot reels and remove them correctly?
- [x] Does the wardrobe work?

**Comment by ezsh** [comment]
There is one more thing that needs to be resolved: collar swapping. To make the refactored code fit better with the future munity quest line (i.e. collar unlocking and removing), I think the clothing data records should mark potentially lockable items. Or do I get it wrong and all the items can be locked by magic? So, what does the "Locked" property in the data record mean and how that is planned work?

I wrote it in the following way: changed the property to "lockable" and made the `Wear()` accept a second parameter `Lock` so that the collar swapping button passes `true` there.

Thanks in advance.

**Comment by ezsh** [comment]
Thank you for the reply! In the meantime I read one more time texts for the introductory scenes and at the Yvonne salon and draw the same conclusion. I will submit a PR fixing the locking.

**Comment by JJM152** [comment]
@ezsh How are we tracking on this? I am leaving for a pretty long vacation (3 weeks) in about 4 days, so I'm keen to push out a 0.8 release within that time frame if possible.

**Comment by ezsh** [comment]
Well, I did not test the game as a whole yet, [the comment above](https://github.com/JJM152/Queen/issues/58#issuecomment-426021079) tracks what you've listed and what I've tested already. Basic things work but I'm not sure about releasing this yet. Let me, please, play from the beginning of the game one more time. I'll do that today or tomorrow.

**Comment by ezsh** [comment]
I guess #85 is the last required fix. If you do not want to commit a proper solution, I will try to do that next week.

**Comment by ezsh** [comment]
> Let me, please, play from the beginning of the game one more time.

Did that up to getting the boarding pass and shopping on land. Thus, "Go" from me.

**Comment by JJM152** [comment]
I'm just adding in a new job right now, #39 and then I'm going to do some play testing myself. We still have like a day or two until I want to push out a release. 

Is there anything you are burning to do? I might throw some new content in...

**Comment by ezsh** [comment]
No, nothing quick comes to mind.

**Comment by JJM152** [comment]
Cool. Closing this out for now. 

Cheers and thanks for all your hard work.
