### ISSUE TITLE
Adding Navigator. 

### ISSUE THREAD

**Issue by panslothda** [JJM152/Queen#6]
Hey there, I was planning on adding a Navigator NPC and a room for him on the Ship. Could be a future place to request specific ports with services or money or get information on how far till next port and what it is.

Is it ok if I add that NPC?

And don't really know where else to contact you except on tfgames forum but there it probably goes under :D

**Comment by JJM152** [comment]
I'm not sure about this because it would require extensive rewrite of something I just put in the game, a mini-map of the ships destination. Check it out in the Captain's room.

**Comment by JJM152** [comment]
I'd rather just leave the ship as it is for now ... if you want to do something why not grab something off my project board :) 

There's also a heap of passages in cities that don't have descriptions yet, add some jobs to some of the other npc's. More TF food is really needed... could itemize some more shops with it (smuggler's den has not much in it).

Just not keen on adding onto the mermaid yet until I figure out how I'm going to do the mutiny later on.

**Comment by panslothda** [comment]
Fair nough :) I can live with that. i will take a look trough the locations and or project board and if i see something I have enough knowledge to help with and if it interests me.

BtW what is your favorite way to be contacted in regards to this kinda questions? tfgames discussion site/ github issue tracker/ email/ discord etc.?

**Comment by JJM152** [comment]
the forum is probably the best way i think

There's seriously a lot of stuff that needs to be done with just itemization. Loot boxes and the such. That would be a huge help even if you did just one

**Comment by panslothda** [comment]
Will try to hrlp out on monday when i got time :)  with itemization you mean creating items?

**Comment by JJM152** [comment]
Yeah, creating items. Could use more TF items I think (people have been asking for them).  More clothes and clothing sets. Adding more clothing to existing sets. It's okay to add more effects to the effects library if you need them to make a cool item.
