### ISSUE TITLE
Defunct code still present in some github files?

### ISSUE THREAD

**Issue by Grengras** [JJM152/Queen#76]
@JJM152  I was checking through the Queen github files online and noticed that a lot of code that belonged to the old alpha system pre-slots is still in place.

For example https://github.com/JJM152/Queen/commit/1258a10bbefbb2793d2a8c9c020b07fc0b27f980

That file contains a lot of code for the dialogue, customer attraction phase, and payouts - all of which went defunct when you switched the game to using its current Slot functionality to handle all of that.

Is this simply stuff you overlooked, or did you plan on bringing this back into the game in some way so left it in deliberately instead?

**Comment by JJM152** [comment]
I just haven't culled it yet. Maybe someone will get around to it... :)
