### ISSUE TITLE
Replace getter function used in twee scripts with proper getters?

### ISSUE THREAD

**Issue by ezsh** [JJM152/Queen#91]
Just to make texts cleaner a bit we could replace `Name()` and similar functions with `get Name()` (and etc.) to save a couple of types and make it read simpler. Opening and issue to discuss the set of functions.

As to me, all argument-less functions in the `Item` class and its successors except of `Charges()` and those acessing `this.Inventory` object can be replaced.

**Comment by JJM152** [comment]
Obviously there's no problem with this, it's just up to you if you want to put the effort into it.  :)
