### ISSUE TITLE
App.EventHandlers.OnLoad (Load save game event handler)

### ISSUE THREAD

**Issue by JJM152** [JJM152/Queen#93]
Versions prior to 0.8 had the old style Player object, but the routine is checking for the PlayerState instead. 

Need to create a player state as well if it doesn't exist in the save file. Then need to copy variables from the old player object to the new player object.

Attached save file from 0.7b
[queen-of-the-seas-v-07b-20181006-233939.zip](https://github.com/JJM152/Queen/files/2453753/queen-of-the-seas-v-07b-20181006-233939.zip)

**Comment by JJM152** [comment]
Got the old save loading now. Had to refactor some stuff

- Internal calls and twee script calls to Equipment instead of using GetEquipmentInSlot 
- Copying data from old Player() object to new PlayerState()

Items seemed to copy just fine, slot reels copied (but lost reel settings, I'll look into that) but wardrobe and equipped items did not copy.

Continuing to fix.

**Comment by ezsh** [comment]
Ooops, apparently I used a post 0.7b game to write that function, but was sure it is 0.7 version. I'm sorry for that.

**Comment by JJM152** [comment]
No worries, almost got it fixed.
