### ISSUE TITLE
Quest to enable favourites

### ISSUE THREAD

**Issue by ezsh** [JJM152/Queen#99]
Add a quest to enable favourites in inventory.

The idea: when inventory list grows to contain more than, say, 15 -- 20 types of items, opening the inventory results in an intermediate passage (only once) with a note that there are too many different items in the locker and it is hard to keep them organised. Then a quest with Julius uncovers to obtain additional boxes and shelves for the cabin.
Julius will of course request to participate in his human experimentations for a few days and keep him in a mood (happy (80)? 85?) for a week to make the boxes. 

Completing the quest unlocks favourites in the inventory and shops.

**Comment by JJM152** [comment]
Like the idea a lot, so :+1: 

This will be hard to implement as quest engine (which is not as advanced as the job one) doesn't have this idea of tracking a stat temporally. You'll have to hack it in:

> Julius will of course request to participate in his human experimentations for a few days and keep him in a mood (happy (80)? 85?) for a week to make the boxes.
